asyncapi/community

README.md
-In my 1:1 today with Lukasz, he noticed that the time mentioned for the AsyncAPI bi-weekly community meetings in the *Community* repo's READme had incorrect information. I'm submitting this PR to fix that.
=> chore: fix READme mention of biweekly community meeting time

.github/workflows/tsc_members_validator/schema.json, .github/workflows/update-website.yml, .github/workflows/validate-tsc-members.yml, TSC_MEMBERS.json
I finally realized that I will never have time to finalize entire TSC members list automation in one run, especially that ya got no skills to do website UI without initial design from someone who has a better sense of esthetics 😄 
- TSC_MEMBERS.json file with the list of all TSC members. Not YAML as it doesn't have to be super human-readable as long term the file is supposed to be updated by the bot + nicely rendered in the AsyncAPI website 
- 2 GH actions workflows 
- one to validate if JSON file has proper structure and if all members added to the file can actually be there according to the open governance model
- another to push new file version to website repo
- this is how we calculate that at the moment there can be only 4 representatives from the same company: …
=> chore: add initial list of TSC members

.github/workflows/EVENTS_ORGANIZATION.md, .github/workflows/create-event-issue.yml, .github/workflows/event_issue_templates/contributor-first.js, .github/workflows/event_issue_templates/sig.js
In recent days we discuss how to make sure our community meetings are visible, and what is the source of truth.
I do not think anyone objects to the current idea of having GitHub Issue per event.
But this is so boring to create these, like seriously, fully manual job and this is why I did not create them for contributor-first meetings.
We need a bit of automation here, especially that more and more meetings will come, @fmvilas will from time to time run Thinking Out Loud, @boyney123 has an idea for another series, and tbh looking at the trend we will grow here even more in the coming months.
> this semi-automation was inspired by a great idea from @MikeRalphson for OAI ([this](https://github.com/OAI/OpenAPI-Specification/blob/main/.github/workflows/agenda.yaml) and …
=> chore: add workflow to semi automate creation of issues related to events

TSC_MEMBERS.json
This PR adds some of the latest repos owned by @magicmatatjahu and @smoya to the list on the TSC members page.
- https://github.com/asyncapi/server-api/pull/18
- https://github.com/asyncapi/parser-go/pull/100
- https://github.com/asyncapi/event-gateway/pull/90
- https://github.com/asyncapi/converter-go/pull/63
- https://github.com/asyncapi/template-for-go-projects/pull/29
cc @magicmatatjahu @derberg @fmvilas
=> chore: update Maciej and Sergio owned repositories list

TSC_MEMBERS.json
Hi all 👋 
As maintainers of [asyncapi/java-template](https://github.com/asyncapi/java-template), we'd like to join the TSC and be more involved with the AsyncAPI community. We are all currently at IBM, and with the 2 current members this keeps us under the per-organisation limit.
Thank you for your consideration and we look forward to hearing from the existing TSC members!
-Dan, Kieran, Tom and Lewis
=> chore: add java-template maintainers to TSC

.github/workflows/create-event-issue.yml, .github/workflows/event_issue_templates/spec-3-0.js, EVENTS_ORGANIZATION.md
Missing: info about where meeting is hosted. Related https://github.com/asyncapi/community/discussions/157#discussioncomment-1963382
This PR added new job that creates issue for new meeting related to AsyncAPI spec 3.0 release
=> chore: add automation for new 3.0 release related meeting

CONTRIBUTING.md
related to https://github.com/asyncapi/.github/pull/94 as the last step to get stuff documented.
I also recorded a video and added it to the guide.
=> chore: extend contributor guide with info about PR merging automation

.github/workflows/create-event-helpers/calendar/index.js, .github/workflows/create-event-helpers/mailchimp/index.js, .github/workflows/send-events-newsletter.yml
Unfortunately, the first attempt to send a newsletter with a meetings list failed. Reason is that when you schedule campaign, it must be at least 24h in the future 🤦🏼 -> https://github.com/asyncapi/community/runs/6121221255?check_suite_focus=true
At the moment this PR introduces simple fix, but it means that because we run cron job midnight Thu/Fri then email with meetings list is sent out not 11:00AM Friday but 11:00AM Saturday.
I'm not 100% sure it is good. 
Other options:
- run the cron job just a day before, Wed/Thu and still send newsletter on Friday. Disadvantage is that meetings hosts need to remember to always schedule meetings latest on Wednesday. Not very bad but still some kind of limitation
- switch from campaign schedule to "immediate" sent, so we run Cron job on Friday 11AM …
=> ci: fix mailchimp campaign schedule with meetings list

.github/workflows/send-events-newsletter.yml
newsletter with meetings list was not sent again :(
I changed it to Sunday which according to https://crontab.guru/#00_00_*_*_7 is 7
but unfortunately, it returns:
apparently, for them Sunday is worth `0`
=> ci: fix sending newsletter sunday cron schedule

.github/workflows/create-event-helpers/issues_templates/spec-3-0.md
Zoom link is not being generated for the issue.
=> ci: add missing zoom link for 3.0 meeting 

TWEET_TOGETHER.md
Current link goes to https://github.com/asyncapi/new/master/?filename=tweets/%3Cyour-tweet-name%3E.tweet, which gives you a nice 404. The link is missing the repository name.
=> docs: fix 'Create new tweet' link

TSC_MEMBERS.json
- Added my details in TSC_members.json file and updated repos for @mcturco.
=> docs: add Akshat Nema as TSC Member

TSC_MEMBERS.json
Add @whitlockjc to `TSC_MEMBERS.json` for [bindings](https://github.com/asyncapi/bindings).
* https://github.com/asyncapi/bindings/pull/141
=> chore(tsc): add @whitlockjc to TSC_MEMBERS.json

TSC_MEMBERS.json
According to https://github.com/asyncapi/spec/pull/846#issuecomment-1274886976, @char0n wants to become member of the TSC, as it is now Code Owner of 3 repositories.
This PR adds @char0n to the list of TSC members + updates the recent repositories @smoya became Code Owner of.
https://github.com/asyncapi/spec/pull/846
=> chore(tsc): add Vladimír Gorej + add repos to Sergio Moya

TSC_MEMBERS.json
=> fix: gitHub username for abir in TSC_MEMBERS.json

new-tool-documentation.md
- Correct filenames in documentation:
- `manual-tools.json` -> `tools-manual.json`
- `automated-tools.json` -> `tools-automated.json`
None
=> docs: correct filenames for manual and automated tools

.github/workflows/create-event-workflow-reusable.yml
When creating meetings, I noticed the meeting banner URL isn't included when adding an event to the calendar :( 
cc @derberg
=> fix: added missing meeting banner env

TSC_MEMBERS.json
- Recently I hand over protobuff schema parser to community
- Modified TSC_MEMBERS.json to add myself as a member
=> chore: add GreenRover to TSC_MEMBERS

.github/workflows/create-event-helpers/calendar/index.js
calendar entry creation fails when hour is 9 because then the end time is `2023-04-26T010:00:00Z` which is bad as it should be `T10` not `T010`.
=> ci: fix meeting scheduling bug when time is 9

.github/workflows/create-event-helpers/issues_templates/spec-3-docs.md, .github/workflows/create-event-spec-3-docs.yml
Adding new OPEN meeting to plan and write Spec 3.0 Docs.
cc @jonaslagoni 
=> docs: new automation for spec 3 docs meetings

.github/workflows/create-event-workflow-reusable.yml
- This PR adds a validation step to the workflow to ensure that the event date is in the future. This prevents scheduling events in the past. Fixes #746 
- Could you please review it?
=> fix: add validation step to check if the event date is in the future.

.github/workflows/maintainer_management.yml, .github/workflows/msg-to-new-member-pr-merged.yml
This PR introduces new jobs to the Welcome New Contributor workflow.
Changes include:
- Added a new job, `add_maintainer`, which invites new maintainers to the organization (ayncapi) and adds them to the team (maintainers). It runs only if new maintainers were identified in the `welcome` job.
- Added a new job `remove_maintainer` which automatically removes maintainers from the organization (asyncapi) and from the maintainers team. This job only runs if removed maintainers are identified.
- Added another job, `display_message`, which posts a welcome message for new maintainers. It depends on the `add_maintainer` job and also only runs if new maintainers were identified.
- Added a job, `update_emeritus` dependent on the `remove_maintainer` job and only runs if …
=> refactor: automate invitation of new maintainers to organization (asyncapi) and team (maintainers)

.github/workflows/create-event-helpers/package-lock.json, .github/workflows/create-event-helpers/package.json, .github/workflows/create-event-helpers/zoom/index.js
Meetings scheduling stopped working because of JWT token support drop in Zoom.
I was getting some notifications beforehand but these were called `jwt deprecation` to take place, so I thought it will still be there for some time 🤷🏼 
anyway, code migrated to work with `server-to-server` auth -> https://developers.zoom.us/docs/internal-apps/s2s-oauth/
works on local like a charm
related to https://github.com/asyncapi/community/actions/runs/6224069021/job/16891419355
=> ci: fix meetings scheduling broken by zoom auth changes

.github/workflows/youtube-to-spotify-for-podcasters.yml
Changes:
- Changed the commit to the latest.
- The latest release commit can be found here: https://github.com/Schrodinger-Hat/youtube-to-anchorfm/releases/tag/v2.3.0
Fixes #951
=> chore: update podcasts workflow to use latest dependency

new-tool-documentation.md
Fixes: #899 
This pull request adds a section : `Adding new category` in the `new-tool-documentation` file in which the process to add a new category for tools is described for the tool owners.
=> docs: add new category section in tools documentation

docs/onboarding-guide/docs-onboarding-checklist.md
Since the goal is automating the `docs contributor onboarding` experience, my name should be removed from such a guide.
=> docs: remove my name from docs onboarding guide

.github/workflows/maintainers-tsc-changes-verification.yaml
- Adds the repo input also to the checkout actions input.
**Testing the workflow change**
Successful run:- https://github.com/ash17290/asyncapi-community/actions/runs/7657528372
Fixes #1024
=> ci: checkout of PR branch is not working

mentorship/summerofcode/2023/README.md
This PRs adds both the proposed and selected projects for last years Google Summer of Code
=> docs: added 2023 gsoc information

WORKING_GROUPS.md, WORKING_GROUPS.yaml
Adds info about how working groups work and an initial WORKING_GROUPS.yaml file with an example on how to define a working group.
Once this is merged. I'll start pinging people so they create individual PRs for the first working groups.
https://github.com/orgs/asyncapi/discussions/1037
=> docs: add info about working groups

WORKING_GROUPS.yaml
Related to https://github.com/orgs/asyncapi/discussions/1037
In addition to @KhudaDad414, @peter-rr, and myself, I suggest additional founding members (please vote by 👍 if you want to join as a funding member)
- @Pakisan: Maintainer of Java bindings and JetBrains IDEA plugin
- @Shurtu-gal: Active contributor in different AsyncAPI projects, and aspiring Studio maintainer
- @princerajpoot20: Studio Design System maintainer
- @ivangsa: Maintainer of [AsyncAPI VS Code extension](https://github.com/asyncapi/vs-asyncapi-preview)
I propose myself as the chairperson (Rotating role) unless there are any objections, I'll be accountable and responsible for the following:
- Manage the overall vision and direction of the working group
- Oversee the development and maintenance of the roadmap
- Mediate …
=> feat: add initial DX working group proposal

AMBASSADORS_MEMBERS.json
Added my info (Giri Venkatesan)
Would like to join the Ambassadors program, as I believe I can contribute to the AsyncAPI community better!
=> chore: update AMBASSADORS_MEMBERS.json

mentorship/summerofcode/README.md, mentorship/summerofcode/application-template.md, mentorship/summerofcode/mentors-guideline.md
This PR includes some of the most important GSoC documentation, such as the following:
- Getting Started Guide
- Application Template
- Mentor's Guideline
cc @alequetzalli @thulieblack
=> docs: added all required GSoC documentations

.github/workflows/youtube-to-spotify-for-podcasters.yml
This PR updated the `youtube-to-anchorfm` action version to the latest version, i.e., v2.4.0.
- [Commit associated with the v2.4.0](https://github.com/Schrodinger-Hat/youtube-to-anchorfm/commit/b02b82f809d24db88472a78c51ffa627f46a6dc3)
- [More information about this release](https://github.com/Schrodinger-Hat/youtube-to-anchorfm/releases/tag/v2.4.0)
PTAL @thulieblack and give the workflow a run after merging this PR. Do let me know how it went... :+1: 
Fixes #1127
=> chore: bump action version to v2.4.0

MAINTAINERS.yaml
This PR updates the list of repositories I own in the `MAINTAINERS.yaml` file. 
Additionally, I'm removing `event-gateway` and `infra` from the list since both are gonna be moved to the archive pretty soon. See https://github.com/orgs/asyncapi/discussions/1045 and https://github.com/asyncapi/infra/issues/62.
=> docs: update list of repos owned by smoya

WORKING_GROUPS.yaml
Recently, the need for a Working Group Co-Chair role has been raised in https://github.com/orgs/asyncapi/discussions/1094#discussioncomment-9197179. 
In order to support that, I suggest we convert the `chairperson` field to `chairpersons`, changing its type to an array of possible chairpersons. 
In case of multiple, and unless specified (via a comment for example), the first one is the primary, the rest are co-chairpersons. Each WG is free to define their own meanings, responsibilities, and limitations of each of those.
cc @thulieblack @fmvilas @AceTheCreator @alequetzalli @Mayaleeeee @derberg
=> chore: allow multiple chairpersons in WORKING_GROUPS.yaml

.github/workflows/create-event-ad-hoc.yml
Adding myself as alternative host, per @smoya's request in Slack for our Maintainer Working Group meetings: https://asyncapi.slack.com/archives/C06GGK7EMSA/p1715080521745239?thread_ts=1714933530.843279&cid=C06GGK7EMSA.
=> chore: add Quetzalli as alternative host

CODEOWNERS
This PR sets the @asyncapi/code_of_conduct team as code owner for the `CODE_OF_CONDUCT.md` and all files under `code_of_conduct` dir.
=> chore: add @asyncapi/code_of_conduct as code owner

.github/workflows/create-event-ad-hoc.yml, .github/workflows/create-event-community-meeting.yml, .github/workflows/create-event-lets-talk-about.yml, .github/workflows/create-event-spec-3-0.yml, .github/workflows/create-event-spec-3-docs.yml, .github/workflows/create-event-thinking-out-loud.yml
Fran shared he is not actually organising meetings atm so better to remove him from alternative hosts.
Fixes https://github.com/asyncapi/community/actions/runs/9566927143/job/26373495416#step:6:23
=> ci: remove fmvilas from alternative hosts list

.github/workflows/vote-verifcation.yml
This update addresses issue #1273 where the GitHub Actions workflow was erroneously triggered by any comment containing the substrings "vote" or "cancel vote." The solution ensures that the workflow only runs when the comment exactly matches /vote or /cancel-vote. By using the == operator for exact string comparison, we prevent unintended activations of the workflow, ensuring precise and correct handling of voting commands.
Fixes #1273
=> ci: update the vote command to match instead of contains

AMBASSADORS_MEMBERS.json
- Adding Hari Krishnan to AMBASSADORS_MEMBERS.json
=> chore: add Hari Krishnan to AMBASSADORS_MEMBERS.json

Emeritus.yaml, MAINTAINERS.yaml
Since we have an automation for voting at the moment and it is easy to even manually check the participation from TSC, I could check who among TSC members did not participate recently.
I reached out to multiple TSC members and as a result we have this PR that refresh some info in TSC list, many responders made commitment that they want to stay (I also explained how easy it is to follow voting through dedicated subscription they can make on this page: https://www.asyncapi.com/community/tsc)
Current number of TSC members is 48 and will be 39 after we merge this PR (waiting for 1 more person to contact me). This means we should get a solid number of at least 38 people that voluntarily want to contribute to healthy growth of AsyncAPI Initiative.
New emeritus (people that are no longer TSC …
=> chore: cleanup TSC list

code_of_conduct/coc-incident-resolution-procedures.md
[Slack Connect](https://slack.com/connect) allows other Slack Workspaces to connect some channels into other Workspaces, in this case, AsyncAPI. 
An example is the [#jsonschema](https://asyncapi.slack.com/archives/C038FTU4LQ6) channel in the AsyncAPI Slack Workspace.
Since there can be confusion about the jurisdiction of the CoC Committee, this PR is an attempt to clarify it.
The idea is that CoC should be enforced in those external channels as well since they are visible in AsyncAPI Slack Workspace.
cc @asyncapi/code_of_conduct @derberg
=> docs: clarify jurisdiction of the CoC Committee regarding Slack external connections

MAINTAINERS.yaml
The maintainer's GitHub username has been changed. According to [this PR](https://github.com/asyncapi/website/pull/3084/files), the new username is `quetzalliwrites` instead of `alequetzalli`.
**Reason**
If this change is not made, the automation will remove the old entry and add a new one. While this may seem beneficial, all the manually set properties will be lost (slack, linkedin, etc.). Therefore, it's better to fix it before the automation.
cc @quetzalliwrites 
- https://github.com/asyncapi/community/issues/1269
=> fix: update invalid GitHub username for Alejandra Quetzalli

AMBASSADORS_MEMBERS.json
Added myself and some of my community activities to the ambassadors page.
=> feat: add Lorna to the ambassadors'

CODE_OF_CONDUCT.md
- Typo in email address in Enforcement section: condcut@asyncapi.io → conduct@asyncapi.io
Resolves #1536
=> fix(COC): typo in email address in Enforcement section

.github/workflows/slack-integration.yml
This PR includes the necessary changes required in the new `ubuntu-latest` image used for the workflow to setup terraform.
As previously discussed with @Shurtu-gal in the issue #1658 the used action in the PR is `hashicorp/setup-terraform@v3 action` and i have tested it by creating a slack workspace and running the workflow similar to one mentioned in the issue.
Here is the [repository](https://github.com/neoandmatrix/terraform) for same.
Resolves #1658 
@Shurtu-gal please review and provide feedback on the PR.
Thanks.
=> fix: terraform setup added

mentorship/summerofcode/2025/asyncapi-gsoc-ideas-page.md
Curated a list of selected project ideas for our participation in the 2025 Google Summer of Code edition
=> docs: add GSoC 2025 project ideas

.github/workflows/maintainer_management.yml, Emeritus.yaml
This PR attempts to fix the HTTP `PUT` request to the GitHub REST API.
It is merged despite some uncertainty, as the necessary conditions can be met only in production environment.
Related to https://github.com/asyncapi/community/issues/1620
=> ci: fix HTTP `PUT` request to the GitHub REST API

.github/workflows/maintainer_management.yml, .github/workflows/maintainers-tsc-changes-verification.yaml
This PR updates the process of passing the authorization token to `with.github-token` by changing it from being passed through `env:` to being passed directly via the `secrets` property.
Related to https://github.com/asyncapi/community/issues/1620
=> ci: update process of passing auth token

.github/workflows/maintainer_management.yml, .github/workflows/maintainers-tsc-changes-verification.yaml, MAINTAINERS.yaml
As the Maintainer (Committer-level) of AsynAPI's `website` repo, I would like to add TRohit20(Self) as a TSC Member. 
FYI, yes, I have gone through the onboarding material to familiarise my responsibilities and the criticality of the role and I accept the same. Material referred to: https://www.youtube.com/watch?v=MfVUUbW2aos?
Last I checked, I am already subscribed to the TSC channel to get mentioned or notified so that end is covered too. 
Additionally, This role and my contributions are purely my independent contributions and are in no way in affiliation with my Full-time employer. 
Thank you @quetzalliwrites & @derberg for the nomination. 
CC @iambami @thulieblack
=> chore: add TRohit20(Self) to TSC as maintainer of website 

AMBASSADORS_MEMBERS.json, Emeritus.yaml, MAINTAINERS.yaml
Signed-off-by: Laurent Broudoux <laurent.broudoux@gmail.com>
Since I have had no time to be more involved as a TSC member for months, I proposed removing myself from the list and becoming an Ambassador. 
- Set the `isTscMember` flag to `false` in `MAINTAINERS.yaml`
- Add my name in Emeritus
- Add a new section in `AMBASSADORS_MEMBERS.json` file
N/A
=> chore(tsc): move `lbroudoux` from TSC to Ambassador
