.github/workflows/validate-tsc-members.yml, TSC_MEMBERS.json
my bad, I left an array of an array as it was needed for the very initial implementation of the son validation, thus calculation of the tsc members would never throw an alert 😅
=> chore: fix list of tsc members to not be array of arrays

CHARTER.md
https://github.com/asyncapi/.github/pull/71
=> chore: move CHARTER.md from .github repo to this repo

tweets/conference-tracks.tweet
Tweet to announce upcoming tracks for the conference.
=> chore: tweet announcing diff tracks for AsyncAPI Conference 2021

.github/workflows/create-event-issue.yml, TSC_MEMBERS.json
because we introduced https://github.com/asyncapi/bindings/pull/98/files and identified new maintainers
list is hard to review as it is ordered, it was ordered with 2nd commit, check 1st commit to see what changed on the list
=> chore(tsc): add Laurent, Gerald, Richard to TSC

TSC_MEMBERS.json
- I am submitting my name to consider being added to the TSC since I am a code owner for the `/website` repo.
=> chore: submitting my name for TSC consideration

TSC_MEMBERS.json
Adding https://github.com/asyncapi/infra to the list of repositories owned by @smoya.
=> chore: add "infra" to repositories owned by Sergio Moya

TSC_MEMBERS.json
- Company change on Jorge's info
=> chore: change Jorge's company in TSC list

TSC_MEMBERS.json
Hi everyone 👋, I am submitting my name to consider being added to the TSC since I am a code owner for the `server-api` repo.
I intend to do my best as a code owner of the `server-api` repo, and to contribute to any project on this amazing community 😃. 
I spoke with @magicmatatjahu to know if there is anything else I need to do, but I think nothing else is necessary.
Let me know if the PR is ok 👍 
Reference: https://github.com/asyncapi/server-api/pull/18#event-5756700207
=> chore: add BOLT04 to TSC members

TSC_MEMBERS.json
Now the limit has gone up per company I would like to join the TSC ⭐️
=> chore(tsc): add David Boyne to TSC members list

TSC_MEMBERS.json
As I'm not able to spend any time on open source right now, I think it's not fair to appear as tsc member or contributor right now, so I'm deleting myself. Hope to colaborate again on the future and keep being such a great community! 🤗
=> chore: remove @jotamusik from TSC members

TSC_MEMBERS.json
Hi
as maintainer and contributor of [java-spring-template](https://github.com/asyncapi/java-spring-template) I would like to join TSC
=> chore: add @Tenischev to TSC list

TSC_MEMBERS.json
Just adding [bundler](https://github.com/asyncapi/bundler/) to @derberg and @Souvikns
=> chore(tsc): add bundler to repo for @derberg and @Souvikns

CODEOWNERS
related https://github.com/asyncapi/community/issues/275
=> chore: fix codeowner files with better bot

TSC_MEMBERS.json
- Modified ` TSC_MEMBERS.json`
=> chore: add @Samridhi-98 as TSC member

TSC_MEMBERS.json
- Recently I became one of the champion contributors of the modelina codebase, hence would like to join TSC.
- Modified `TSC_MEMBERS.json` to add myself as a member
=> chore: add @ron-debajyoti as TSC member

.github/workflows/validate-tsc-members.yml, TSC_MEMBERS.json
Just changing my `availableForHire` and `Company`. 
=> chore(tsc): update company status for @Souvikns

.github/workflows/event_issue_templates/spec-3-0.js
This PR adds links to the live stream as well as the zoom link.
=> chore: adapt spec 3.0 template to include links

TSC_MEMBERS.json
Updated company in TSC Members list
=> chore(tsc): update David Boyne company name

TSC_MEMBERS.json
- I would like to join TSC to provide guidance in the area of visual & product design
- I have added my information to the `TSC_MEMBERS.json` file
=> chore: add @mcturco as TSC Member

tweets/looking-for-release-coordinator-2_5.tweet
https://github.com/asyncapi/community/discussions/418
=> chore(tweet): look for release coordinator volunteers

.github/workflows/create-event-ad-hoc.yml, .github/workflows/create-event-community-meeting.yml, .github/workflows/create-event-lets-talk-about.yml
Ace would love to be added as an alternative host for create event community meeting
=> feat: add ace as an alternative host for this meeting

TSC_MEMBERS.json
Just changing my `availableForHire` and `company`.
None
=> chore(tsc): update company status for @ron-debajyoti

TSC_MEMBERS.json
Description
I would like to join TSC as maintainer of [vs-asyncapi-preview](https://github.com/asyncapi/vs-asyncapi-preview)
I have added my information to the TSC_MEMBERS.json file
=> chore(tsc): add @ivangsa to TSC_MEMBERS.json

.github/workflows/notify-tsc-members-mention.yml, .github/workflows/scripts/mailchimp/htmlContent.js, .github/workflows/scripts/mailchimp/index.js, .github/workflows/scripts/mailchimp/package-lock.json, .github/workflows/scripts/mailchimp/package.json
- eventually, this PR should show up here https://github.com/asyncapi/.github
- for now, I just make changes in `community` repo basically to test it in one repo before it is rolled out to other repos
- once we see it works well here, I will open PR in `.github`
See also https://github.com/asyncapi/.github/issues/191
=> ci: add automation to schedule email to TSC members

TSC_MEMBERS.json
This PR adds @aeworxet as a TSC member for maintenance of project [bundler](https://github.com/asyncapi/bundler).
=> chore(tsc): add @aeworxet as a new TSC member

.github/workflows/create-event-helpers/mailchimp/index.js, .github/workflows/scripts/mailchimp/index.js, .gitignore
This PR is fixing a bug that was sending the weekly meetings email to all the people in our Mailchimp list, instead of just the ones subscribed to this kind of notification.
=> fix: emails not being sent to proper recipients

TSC_MEMBERS.json
- add myself to the members list.
[Pulsar binding PR](https://github.com/asyncapi/bindings/pull/173)
=> chore: add myself to the members list.

TSC_MEMBERS.json
update company name for @khudadad414
=> feat: update company name for @khudadad414

AMBASSADORS_MEMBERS.json
I added some additional fields to the ambassador lists which include ambassador image and bio 
cc @derberg
=> feat: extended ambassadors.json

TSC_MEMBERS.json
- This PR adds @pratik2315 as a TSC member for the maintenance of project [generator](https://github.com/asyncapi/generator).
=> chore(tsc): add @pratik2315 as a TSC member

TSC_MEMBERS.json
Add Abir `imabp`, to the TSC Members JSON.
cc: @magicmatatjahu
=> feat: add Abir to TSC member json for problem repo

AMBASSADORS_MEMBERS.json
After discussions with @Barbanio ; i submit this pr in order to be recognized as AsyncApi Ambassador :)
Two talks are coming in the next three months in tech companies
=> chore: add ldussart to the ambassafor program

GOVERNANCE.md
As per [point 2.2 of the charter](https://github.com/asyncapi/community/blob/master/CHARTER.md?plain=1#L33), there should be a GOVERNANCE.md file containing information about who's the current Executive Director. So I'm adding it.
My idea is to keep working on this file so this is just the first of multiple PRs.
Fixes #198
=> chore: add governance file

.github/workflows/create-event-ad-hoc.yml, .github/workflows/create-event-community-meeting.yml, .github/workflows/create-event-lets-talk-about.yml
add me 😁😁 as an alternative host for meetings
=> feat: add Thulie as an alternative host for meetings

.github/workflows/tsc_members_validator/schema.json, CODEOWNERS, TSC_MEMBERS.json
- Added Slack IDs of all TSC members
Resolves #617
=> feat: add slack IDs of all Members

TSC_MEMBERS.json
Hi everyone,
I recently joined the AsyncAPI Initiative working on `modelina` and would love to be included in the TSC.
Cheers,
Kenneth
=> chore(tsc): add @kennethaasan to TSC list

.github/workflows/msg-to-new-member-pr-merged.yml
Updating the name of the Slack token environment variable as per the repo.
=> ci: changed slack token name

PROJECT_FINANCE.md
goal of this PR is to clarify in one MD file not only how people can sponsor us but also what we spend money on.
it will make it super easy for me to share it with different companies to have a good argument for them to be our sponsors
cc @thulieblack 
@alequetzalli 🙏🏼
=> docs: update project finance doc with info about what we spend money on

TSC_MEMBERS.json
As I'm stepping down from my contributor role in modelina, I'm also stepping down from the TSC for the same reasons.
Thanks for having me. <3
https://github.com/asyncapi/modelina/pull/1275
=> chore(tsc): remove LouisXhaferi from tsc members

GOVERNANCE.md
Alright! Let's make it official!
=> chore: add Lukasz as director

TSC_MEMBERS.json
Since now @KhudaDad414 and I are code owners of glee, I am updating tsc JSON file to reflect that.
=> feat: add glee to repo for me and khuda

.github/workflows/create-event-workflow-reusable.yml
=> ci: fix syntax error

AMBASSADORS_MEMBERS.json
And also rewrite his description
- ...
- ...
- ...
=> chore: update Ludovic Dussart events

CODEOWNERS, TSC_MEMBERS.json
Adding the lovely Community Manager to the list🤩
=> chore: add Thulie to the TSC list

MAINTAINERS.yaml
I have added my details to the yaml file.
Thank you.
=> chore(tsc): add Maya as TSC member

CONTRIBUTING.md
Fixed a typo in [CONTRIBUTING.md](CONTRIBUTING.md). See Related issue(s) for more.
[Issue #795](https://github.com/asyncapi/community/issues/795#issue-1794978277)
=> docs: fix typo in contributing file

Emeritus.yaml
This PR adds a new file named `Emeritus.yaml` that lists individuals who were previously maintainers but are no longer active.
=> chore: add Emeritus.yaml file

MAINTAINERS.yaml
This pull request updates all GitHub handles to be in lowercase in the `MAINTAINERS.yaml` file.
=> refactor: update all the github handles to be lower case

.github/workflows/create-event-helpers/zoom/index.js
meeting schedule still do not work
- https://github.com/asyncapi/community/commit/5df2c2657d53b7374e3208a56b11a62eb72500bc did not fix it
- on local works like a charm
- I checked secrets, and these are good
need some debug info
=> ci: add debug info to meetings workflows

MAINTAINERS.yaml
- Added my details in `Maintainers.yaml`
[studio/862](https://github.com/asyncapi/studio/pull/862)
=> chore(tsc): add Prince Rajpoot as new TSC member.

MAINTAINERS.yaml
As a code maintainer of `github-action-for-cli` I would like to apply for TSC.
Thanks
=> chore(tsc): add Ashish Padhy as a new TSC member

AMBASSADORS_MEMBERS.json
=> chore(ambassador): update ldussart contributions for 2023

MAINTAINERS.yaml
- Added my details in Maintainers.yaml
[modelina/1647](https://github.com/asyncapi/modelina/pull/1647)
=> chore(tsc): add Ashmit JaiSarita Gupta as new TSC member

MAINTAINERS.yaml
As a code maintainer of Studio I would like to apply for TSC.
Thanks
=> chore(tsc): add Samir AMZANI as a new TSC member

AMBASSADORS_MEMBERS.json
Update on Alejandra's contributions as an ambassador. 
@alequetzalli, would you mind to take a look at this, please? Thank you 🙂
=> chore: contributions by Alejandra 2023

MAINTAINERS.yaml
As a triage code maintainer for `website` I would like to apply for TSC.
Thanks
cc: @derberg @thulieblack
=> chore(tsc): add Sambhav Gupta as a new TSC member

MAINTAINERS.yaml
There is a minor spelling mistake in maintainers.yaml .This PR aims to fix that issue
=> fix: minor spelling fix in maintainers.yaml

MAINTAINERS.yaml
This PR adds @aeworxet as a maintainer.
=> chore: add aeworxet as a maintainer

WORKING_GROUPS.yaml
Revert https://github.com/asyncapi/community/pull/1088 TSC should give the :+1: 
https://github.com/asyncapi/community/blob/master/WORKING_GROUPS.md
=> chore: revert DX working group

mentorship/summerofcode/2024/asyncapi-gsoc-ideas-page.md
added newly proposed project ideas and removed outdated ones 
cc @thulieblack @alequetzalli @derberg
=> docs: updated list of project ideas

mentorship/summerofcode/2024/asyncapi-gsoc-ideas-page.md
Updated the mentors on the `Configure and add tests for scripts` and `Conference Website Maintainance` project ideas
=> docs: update asyncapi-gsoc-ideas-page.md

WORKING_GROUPS.yaml
Related to https://github.com/orgs/asyncapi/discussions/1099
=> feat: adding Developer Experience Working group

.github/workflows/vote-verifcation.yml
Followup: #1120 
* Add new GitHub secret
* Improve the response message
=> ci: update github action and improve comment

.github/workflows/vote-verifcation.yml
Followup: #1093 
* Add new GitHub token in step
=> ci: add bot github token to workflow for voting verification

WORKING_GROUPS.yaml
I want to be part of the DX working group.
@Amzani @Pakisan @KhudaDad414 @ivangsa @peter-rr @Shurtu-gal @princerajpoot20 @Mayaleeeee
=> chore: added myself to the DX working group

MAINTAINERS.yaml
I won't be able to devote much time to AsyncAPI soon, so I will not be able to continue as a maintainer. Thanks for everything! 💜
cc @thulieblack @derberg
=> chore: remove @Barbanio as maintainer

MAINTAINERS.yaml, TSC_MEMBERS.json
=> fix: change the username to valid one

TSC_MEMBERS.json
I won't be able to devote much time to AsyncAPI soon, so I cannot continue as a TSC member. Thanks for everything! 💜
@asyncapi/tsc_members
=> chore: remove `Barbanio` from TSC members

Emeritus.yaml
Since I will not continue in the TSC (#1168), I request to add me as emeritus.
=> chore: add `Barbanio` as emeritus

WORKING_GROUPS.yaml
- This fixes the error in `WORKING_GROUPS.yaml` file.
Relates to https://github.com/asyncapi/community/pull/1131
=> chore: fix working groups file

.github/workflows/slack-integration.yml
> [!IMPORTANT]
> @derberg could you add the secret before merging this.
See also #1131
=> chore: change SLACK_TOKEN to SLACK_INFRA_TOKEN

.github/workflows/slack-integration.yml
=> ci: watch the slack workflow for changes as well

WORKING_GROUPS.yaml
-  Added myself to the conference working group
- ...
- ...
=> chore: add bami to conference wg

.github/workflows/create-event-ad-hoc.yml
Fixes https://github.com/asyncapi/community/issues/1218
=> chore: add samir.amzani in alternative hosts list

MAINTAINERS.yaml
Add `anshgoyalevil` as the maintainer for website repo.
=> chore: add anshgoyalevil as website maintainer

MAINTAINERS.yaml
=> feat: update the user name of the TSC member

WORKING_GROUPS.yaml
Adding Aayush to Developer Experience group
=> chore: add aayush to developer experience group  of Asyncapi

WORKING_GROUPS.yaml
=> fix: quote sentence with colon character in WORKING_GROUPS.yaml

.github/workflows/create-event-ad-hoc.yml
- Added oluwabamikemi@gmail.com to the alternate hosts.
=> chore: add bami to event hosts (Update create-event-ad-hoc.yml)

.github/workflows/create-event-ad-hoc.yml
I corrected the misspelled email address.
=> chore: update create-event-ad-hoc.yml

AMBASSADORS_MEMBERS.json
Adding myself to the list of Ambassadors by invitation from Thulie.
=> chore: add Raphael De Lio to AMBASSADORS_MEMBERS.json

AMBASSADORS_MEMBERS.json
=> chore: update ambassadors profile

MAINTAINERS.yaml
=> chore: update usernames for maintainers

mentorship/asyncapi-mentorship/README.md
=> docs: update README.md

AMBASSADORS_MEMBERS.json
=> fix: add missing img

CODE_OF_CONDUCT.md
Add the correct link to the procedure docs instead of pointing to the PR
=> chore: update coc doc

MAINTAINERS.yaml
removing postman affiliation for few TSC members
=> chore: update postman info

MAINTAINERS.yaml
Added @ashmit-coder for maintainer of `conference-website`
=> feat: added ashmit-coder in Maintainers.yml

AMBASSADORS_MEMBERS.json
- Updating contributions under Hari Krishnan in Ambassadors section
=> docs: update contributions under Hari Krishnan in Ambassadors list

MAINTAINERS.yaml
add aayushsaini as maintainer of CLI
=> chore: add AayushSaini101 to TSC as maintainer of cli

.github/workflows/update-docs-in-website.yml
update the changes on the docs automation to the website
=> feat: update docs automation

.github/workflows/maintainers-tsc-changes-verification.yaml, MAINTAINERS.yaml
Updating my company and `availableForHire` status.
=> chore: update @Souvikns company status and fixing verification workflow

mentorship/summerofcode/2025/asyncapi-gsoc-ideas-page.md
This PR targets adding GSOC-related ideas of the website.
=> feat: add website GSoC 2025 ideas

.github/workflows/maintainer_management.yml
This PR introduces minor fixes to the workflow.
=> ci: minor fixes to the maintainers management workflow

MAINTAINERS.yaml
Add @cdavernas to TSC as maintainer of net-sdk
=> chore: add cdavernas to TSC as maintainer of net-sdk

MAINTAINERS.yaml
Add @vishvamsinh28 to TSC as maintainer of website
=> chore: add vishvamsinh28 to TSC as maintainer of website

MAINTAINERS.yaml
Add @jbbianchi to TSC as maintainer of net-sdk
=> chore: add jbbianchi to TSC as maintainer of net-sdk

.github/workflows/maintainer_management.yml
followup from https://github.com/asyncapi/community/actions/runs/14010907767/job/39285904814
=> chore: fix message display for new maintainers and put more details

AMBASSADORS_MEMBERS.json
- Add missing link on Laurents contributions
- Update Hugo's socials and company
=> chore: update ambassadors file

docs/onboarding-guide/maintainer-guide.md
This PR fixes redundant bold formatting for headings in the https://www.asyncapi.com/docs/community/onboarding-guide/maintainer-guide
See also #1638
=> docs: remove redundant bold formatting for headings
